<x-livewire-tables::bs5.table.cell>
    {{$row->kode}}
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell>
    {{$row->nama_produk}}
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell>
    {{$row->produkSubKategori->nama_sub_kategori}}
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell>
    {{$row->harga}}
</x-livewire-tables::bs5.table.cell>
<x-livewire-tables::bs5.table.cell>
    <x-atoms.btn-dropdown-table>
        <x-atoms.btn-dropdown-menu-table :href="route('pegawai.show', $row->id)">
            View
        </x-atoms.btn-dropdown-menu-table>
        <x-atoms.btn-dropdown-menu-table>
            Delete
        </x-atoms.btn-dropdown-menu-table>
    </x-atoms.btn-dropdown-table>
</x-livewire-tables::bs5.table.cell>
